apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: anonimchat-data
  name: anonimchat-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
