apiVersion: v1
data:
  init.sql: |
    USE my_database;

    CREATE TABLE messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        content TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: anonimchat-database
  name: anonimchat-database-cm1
