apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: anonimchat-database
  name: anonimchat-database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: anonimchat-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: anonimchat-database
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: my_database
            - name: MYSQL_PASSWORD
              value: my_password
            - name: MYSQL_ROOT_PASSWORD
              value: my_secret_password
            - name: MYSQL_USER
              value: my_user
          image: mysql:8.0
          name: anonimchat-database
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: anonimchat-data
            - mountPath: /docker-entrypoint-initdb.d
              name: anonimchat-database-cm1
      restartPolicy: Always
      volumes:
        - name: anonimchat-data
          persistentVolumeClaim:
            claimName: anonimchat-data
        - configMap:
            name: anonimchat-database-cm1
          name: anonimchat-database-cm1
