apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/vboxuser/kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: anonimchat
  name: anonimchat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: anonimchat
  template:
    metadata:
      annotations:
        kompose.cmd: /home/vboxuser/kompose -f docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: anonimchat
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: my_database
            - name: MYSQL_HOST
              value: anonimchat-database
            - name: MYSQL_PASSWORD
              value: my_password
            - name: MYSQL_USER
              value: my_user
          image: docker.io/ujinpavlovich/anonimmchat:latest
          name: anonimchat
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
