apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: anonimchat
  name: anonimchat
spec:
  replicas: 1
  selector:
    matchLabels:
      name: anonimchat
  template:
    metadata:
      labels:
        name: anonimchat
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: my_database
            - name: MYSQL_HOST
              value: anonimchat-database
            - name: MYSQL_PASSWORD
              value: my_password
            - name: MYSQL_USER
              value: my_user
          image: docker.io/ujinpavlovich/anonimmchat:latest
          name: anonimchat
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
